on: [push, pull_request]

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

jobs:
  test-python:
    # "cannot specify version when calling local workflows"
    uses: ./.github/workflows/test-python.yml
  
  # Give up on directly reusing workflows die to lack of repo permissions  
  build-docs:
    uses: ./.github/workflows/build-docs.yml

    
  deploy-docs:
    uses: ./.github/workflows/deploy-docs.yml
    with:
      pages_artifact_name: ${{ needs.build-docs.outputs.pages_artifact_name }}
    if: ${{ github.ref_name == 'main' || github.head_ref == 'main'}} && github.event_name != 'pull_request'
    needs: [test-python, build-docs]
