on: [push, pull_request]

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read


jobs:
  test-python:
    # "cannot specify version when calling local workflows"
    uses: ./.github/workflows/test-python.yml
  
  build-docs:
    uses: NERC-CEH/dri-cicd/.github/workflows/build-docs.yml@main

  deploy-docs:
    uses: NERC-CEH/dri-cicd/.github/workflows/deploy-docs.yml@main
    with:
      pages_artifact_name: ${{ needs.build-docs.outputs.pages_artifact_name }}
    if: ${{ github.ref_name == 'main' || github.head_ref == 'main'}}
    needs: [test-python, build-docs]
